Fix for bioMaterial page exception
javax.el.ELException: The identifier [class] is not a valid Java identifier

was caused by the use of java reserved word 'class' in bioMaterial.detail.jsp:136