Possible fix for exception being thrown when fetching batch info
Was throwing
java.lang.NoClassDefFoundError: Could not initialize class org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl

It seems that the necessary library is being bundled with the JRE and adding
this dependency is causing problems.